name: date_calc
description: Date manipulation library for Dart.
version: 0.0.1
author: makicamel <unright@gmail.com>
homepage: https://github.com/makicamel/date_calc

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: '>=1.0.0'

dev_dependencies:
  test: ^1.6.3
